import frappe


ACCOUNT_CODES = [
	{"acmastcode": "1", "ac_code": "B101", "ac_name": "RECURRING DEPOSIT PLAN2"},
	{"acmastcode": "2", "ac_code": "B102", "ac_name": "FIXED DEPOSIT PLAN 2"},
	{"acmastcode": "3", "ac_code": "B103", "ac_name": "SECURITY DEPOSITS"},
	{"acmastcode": "4", "ac_code": "B104", "ac_name": "RECURRING DEPOSIT PLAN1"},
	{"acmastcode": "18", "ac_code": "K201", "ac_name": "ADVANCES TO EMPLOYEES"},
	{"acmastcode": "19", "ac_code": "K102", "ac_name": "PERSONAL LOAN"},
	{"acmastcode": "20", "ac_code": "K103", "ac_name": "STAFF LOAN ACCOUNT"},
	{"acmastcode": "21", "ac_code": "K203", "ac_name": "ADVANCES  TO BRANCH OPENING"},
	{"acmastcode": "22", "ac_code": "K104", "ac_name": "GROUP LOAN"},
	{"acmastcode": "23", "ac_code": "K105", "ac_name": "TARAN LOAN"},
	{"acmastcode": "24", "ac_code": "K206", "ac_name": "OTHER ADVANCES"},
	{"acmastcode": "25", "ac_code": "K107", "ac_name": "GROUP TARAN"},
	{"acmastcode": "26", "ac_code": "K108", "ac_name": "LOAN AGAINST FD"},
	{"acmastcode": "27", "ac_code": "K210", "ac_name": "GOAT LOAN ISSUE"},
	{"acmastcode": "40", "ac_code": "R106", "ac_name": "PROCESSING FEES"},
	{"acmastcode": "56", "ac_code": "X101", "ac_name": "OFFICE MAINTENANCE"},
	{"acmastcode": "60", "ac_code": "X105", "ac_name": "STAFF SALARY EXPENSE"},
	{"acmastcode": "68", "ac_code": "X113", "ac_name": "AGENT COMMISSION PAID"},
	{"acmastcode": "71", "ac_code": "X116", "ac_name": "MISC EXPENSES"},
	{"acmastcode": "72", "ac_code": "X117", "ac_name": "OFFICE RENT A\\C"},
	{"acmastcode": "122", "ac_code": "Y103", "ac_name": "INTEREST PAID - RECURRING DEPOSIT"},
	{"acmastcode": "142", "ac_code": "AGNT", "ac_name": "AGENT"},
	{"acmastcode": "143", "ac_code": "SAV", "ac_name": "SAVING DEPOSIT"},
	{"acmastcode": "148", "ac_code": "DAM", "ac_name": "DAMDUPPAT DEPOSIT AC"},
	{"acmastcode": "149", "ac_code": "FD", "ac_name": "MONTHLY INCOME SCHEME DEPOSIT"},
	{"acmastcode": "152", "ac_code": "PERLON", "ac_name": "PERSONAL LOAN OF SALARY"},
	{"acmastcode": "154", "ac_code": "RD", "ac_name": "RECURRING DEPOSIT"},
	{"acmastcode": "155", "ac_code": "SKBG", "ac_name": "SAHAYOG KISAN BACHAT GAT"},
	{"acmastcode": "157", "ac_code": "B108", "ac_name": "CURRENT ACCOUNT"},
	{"acmastcode": "159", "ac_code": "K109", "ac_name": "SALARY LOAN"},
	{"acmastcode": "160", "ac_code": "INV", "ac_name": "NON OF USE"},
	{"acmastcode": "194", "ac_code": "B107", "ac_name": "DAILY DEPOSIT"},
	{"acmastcode": "195", "ac_code": "DLYLO", "ac_name": "TARAN AGAINST DAILY DEPOSIT"},
	{"acmastcode": "196", "ac_code": "INDLO", "ac_name": "INDIVIDUAL LOAN"},
	{"acmastcode": "216", "ac_code": "DD", "ac_name": "DAILY DEPOSIT"},
	{"acmastcode": "221", "ac_code": "K106", "ac_name": "C.C.LIMIT"},
	{"acmastcode": "223", "ac_code": "K202", "ac_name": "MOBILE ADVANCE"},
	{"acmastcode": "233", "ac_code": "LFD", "ac_name": "LOCKER SECURITY DEPOSIT"},
	{"acmastcode": "245", "ac_code": "K110", "ac_name": "TERM LOAN"},
	{"acmastcode": "247", "ac_code": "FD3", "ac_name": "FIXED DEPOSITS PLAN 3"},
	{"acmastcode": "250", "ac_code": "K111", "ac_name": "DATTAK GRAM LOAN"},
	{"acmastcode": "255", "ac_code": "SHLINK", "ac_name": "SHARE LINKAGE ACCOUNT"},
	{"acmastcode": "256", "ac_code": "B105", "ac_name": "AGENT SECURITY DEPOSIT"},
	{"acmastcode": "269", "ac_code": "PF", "ac_name": "EMPLOYEE PROVIDENT FUND"},
	{"acmastcode": "272", "ac_code": "SWF", "ac_name": "STAFF WELFARE FUND"},
	{"acmastcode": "273", "ac_code": "PT", "ac_name": "EMPLOYEE PROFESSIONAL TAX"},
	{"acmastcode": "275", "ac_code": "ITS", "ac_name": "INCOME TAX SALARY (92B)"},
	{"acmastcode": "287", "ac_code": "INVADM", "ac_name": "INVESTMENT IN AADHAR MULTISTATE"},
	{"acmastcode": "288", "ac_code": "B109", "ac_name": "RETIREMENT FUTURE FUND"},
	{"acmastcode": "290", "ac_code": "SH", "ac_name": "SHARE ACCOUNT"},
	{"acmastcode": "305", "ac_code": "K205", "ac_name": "PURPOSE ADVANCE A/C"},
	{"acmastcode": "306", "ac_code": "K205", "ac_name": "PURPOSE ADVANCE A/C"},
	{"acmastcode": "314", "ac_code": "PL", "ac_name": "PROFIT & LOSS"},
	{"acmastcode": "324", "ac_code": "B110", "ac_name": "AGENT SECURITY A/C"},
	{"acmastcode": "328", "ac_code": "AGNSUS", "ac_name": "AGENT SUSPENSE A/C"},
	{"acmastcode": "338", "ac_code": "EMSAAD", "ac_name": "EMPLOYEES SALARY ADVANCE"},
	{"acmastcode": "343", "ac_code": "K112", "ac_name": "SMALL BUSINESS LOAN"},
	{"acmastcode": "350", "ac_code": "MOBAPP", "ac_name": "MOBILE APP"},
	{"acmastcode": "352", "ac_code": "BACHTL", "ac_name": "JOINT LIABILITIES  LOAN"},
	{"acmastcode": "365", "ac_code": "VL", "ac_name": "VEHICLE LOAN"},
	{"acmastcode": "373", "ac_code": "USEVL", "ac_name": "USE TWO WHEELER LOAN"},
	{"acmastcode": "374", "ac_code": "EMPINS", "ac_name": "EMPLOYEES INSURANCE"},
	{"acmastcode": "377", "ac_code": "VLGSA", "ac_name": "NOT USE (VEHICAL LOAN GUARANTOR SAVINGS)"},
	{"acmastcode": "380", "ac_code": "JLLEXE", "ac_name": "JLL EXECUTIVE"},
	{"acmastcode": "383", "ac_code": "TAVL", "ac_name": "TRADING ADVANCE VEHICAL LOAN"},
	{"acmastcode": "385", "ac_code": "BACSAV", "ac_name": "JLL SAVING A/C"},
	{"acmastcode": "386", "ac_code": "HSLO", "ac_name": "HOSPITAL AND SCHOOL STAFF LOAN"},
	{"acmastcode": "389", "ac_code": "VLMIS", "ac_name": "VEHICLE LOAN MISCELLANEOUS"},
	{"acmastcode": "392", "ac_code": "INVESA", "ac_name": "INVESTMENT IN ESAF SMALL FINANCE BANK"},
	{"acmastcode": "405", "ac_code": "EHOLO", "ac_name": "EMPLOYEES HOME LOAN"},
	{"acmastcode": "418", "ac_code": "BDE", "ac_name": "BUSINESS  DEVELOPMENT EXECUTIVE"},
	{"acmastcode": "419", "ac_code": "UNT", "ac_name": "UNTRACEABLE"},
	{"acmastcode": "421", "ac_code": "VL21", "ac_name": "SEASON SCHEME VEHICLE LOAN 21"},
	{"acmastcode": "431", "ac_code": "SILSAV", "ac_name": "SILVER SAVING AC"},
	{"acmastcode": "432", "ac_code": "FD4", "ac_name": "FIXED DEPOSIT PLAN 4"},
	{"acmastcode": "435", "ac_code": "PURPO", "ac_name": "PURPOSE ADVANCE ACCOUNTS"},
	{"acmastcode": "437", "ac_code": "PURPO", "ac_name": "PURPOSE ADVANCE ACCOUNTS"},
	{"acmastcode": "442", "ac_code": "CUGOLD", "ac_name": "CURRENT GOLD ACCOUNT"},
	{"acmastcode": "444", "ac_code": "CUWEAL", "ac_name": "CURRENT WEALTH ACCOUNT"},
	{"acmastcode": "445", "ac_code": "SAVSIL", "ac_name": "SAVING SILVER ACCOUNT"},
	{"acmastcode": "448", "ac_code": "INVBOB", "ac_name": "INVESTMENT IN BANK OF BARODA"},
	{"acmastcode": "451", "ac_code": "EVL", "ac_name": "ELECTRIC VEHICLE LOAN"},
	{"acmastcode": "453", "ac_code": "SWEES", "ac_name": "SAHAYOG WOMAN E.E.SCHEME"},
	{"acmastcode": "457", "ac_code": "EMPRLO", "ac_name": "EMPLOYEES PERSONAL LOAN"},
	{"acmastcode": "466", "ac_code": "LWF", "ac_name": "LABOUR WELFARE FUND EMPLOYEE"},
	{"acmastcode": "474", "ac_code": "DDLOAN", "ac_name": "DAILY DEPOSIT LOAN"},
	{"acmastcode": "480", "ac_code": "BRNET", "ac_name": "BR NET JOINT LIABILITY LOAN"},
	{"acmastcode": "482", "ac_code": "HOSCLO", "ac_name": "STAFF OF HOSPITAL AND SCHOOL LOAN"},
	{"acmastcode": "492", "ac_code": "DDGIFT", "ac_name": "DAILY DEPOSIT GIFT"},
	{"acmastcode": "500", "ac_code": "JLLSUS", "ac_name": "JLL EXECUTIVE SUSPENSE AC"},
	{"acmastcode": "501", "ac_code": "INDRD", "ac_name": "INDIAN BANK RD Ac 7393401276"},
	{"acmastcode": "503", "ac_code": "BLLOAN", "ac_name": "BUSINESS  LOAN ACCOUNT"},
	{"acmastcode": "514", "ac_code": "INVCEB", "ac_name": "INVESTMENT IN CENTRAL BANK OF INDIA"},
	{"acmastcode": "517", "ac_code": "VL23", "ac_name": "VEHICAL LOAN INT  2023"},
	{"acmastcode": "519", "ac_code": "INVSGB", "ac_name": "INVESTMENT IN SAHAYOG GRAMIN BIGAR SHETT"},
	{"acmastcode": "520", "ac_code": "INVJNP", "ac_name": "INVESTMENT IN JANHIT NAGRI SAH PAT SANSTHA"},
	{"acmastcode": "521", "ac_code": "EMINRE", "ac_name": "EMPLOYEE INSURANCE REIMBURSMENT"},
	{"acmastcode": "533", "ac_code": "MOBAIL", "ac_name": "MOBAILE LOAN"},
	{"acmastcode": "548", "ac_code": "EVLSS", "ac_name": "EVL SPECIAL SCHEME 10.99"},
	{"acmastcode": "557", "ac_code": "VL24", "ac_name": "VL SPECIAL SCHEME 24"},
	{"acmastcode": "559", "ac_code": "SAVSCH", "ac_name": "SAVING SCHOOL"},
	{"acmastcode": "561", "ac_code": "INVYUB", "ac_name": "INVESTMENT IN  THE YAVATMAL URBAN CO OP BANK"},
	{"acmastcode": "564", "ac_code": "BSD", "ac_name": "BUILDING SECURITY DEPOSIT"},
	{"acmastcode": "568", "ac_code": "INVPNB", "ac_name": "INVESTMENT IN PANJAB NATIONAL BANK"},
	{"acmastcode": "599", "ac_code": "JLLRD", "ac_name": "JOINT LIABILITY RECURRING DEPOSIT"},
	{"acmastcode": "605", "ac_code": "JLLSA", "ac_name": "JOINT LIABILITY SAVING ACCOUNT"},
	{"acmastcode": "609", "ac_code": "INVHDF", "ac_name": "INVESTMENT IN HDFC BANK"},
	{"acmastcode": "615", "ac_code": "FDL60", "ac_name": "FD TARAN 60 PERCENT"},
	{"acmastcode": "617", "ac_code": "FDL70", "ac_name": "FD TARAN 70 PERCENT"},
	{"acmastcode": "618", "ac_code": "DAML50", "ac_name": "DAMDUPPAT TARAN 50"},
	{"acmastcode": "619", "ac_code": "DAMTL6", "ac_name": "DAMDUPPAT TARAN 60 PERCENT"},
	{"acmastcode": "620", "ac_code": "DAMTL7", "ac_name": "DAMDUPPAT TARAN 70 PERCENT"},
	{"acmastcode": "621", "ac_code": "DAMTL8", "ac_name": "DAMDUPPAT TARAN 80 PERCENT"},
	{"acmastcode": "622", "ac_code": "DAMOD", "ac_name": "DAMDUPPAT OVER DRAFT"},
	{"acmastcode": "623", "ac_code": "FDL50", "ac_name": "FD TARAN 50 PERSENT"},
	{"acmastcode": "627", "ac_code": "TASSIL", "ac_name": "TASC SAVING SILVER"},
	{"acmastcode": "628", "ac_code": "TASCUW", "ac_name": "TASC CURRENT WEALTH"},
	{"acmastcode": "635", "ac_code": "ESIC", "ac_name": "ESIC PAYABLE"},
	{"acmastcode": "649", "ac_code": "NPS", "ac_name": "NATIONAL PENSION SCHEME"},
	{"acmastcode": "652", "ac_code": "ADUSCH", "ac_name": "EDUCATION SCHIME"},
]


def get_context(context):
	context.no_cache = 1
	context.no_header = 1
	context.full_width = 1
	context.api_base_url = frappe.db.get_single_value("Netwin Settings", "api_base_url") or ""
